# swees <sweespay.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
]

[DOCUMENTATION]
ORG_NAME="sweespay"
ORG_URL="https://sweespay.github.io/"
ORG_LOGO ="https://sweespay.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="sweespay@proton.me"
ORG_SUPPORT_EMAIL="sweespay@proton.me"
ORG_DESCRIPTION=": POWER BUY SWEESSCUTODY"

[[PRINCIPALS]]
email="non"

[[CURRENCIES]]
code ="001"
name ="001"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/crown.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


[[CURRENCIES]]
code ="SGB"
name ="SWEES GOLD BOND"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/SGB.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="0oo"
name ="0oo"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="1"
name ="1"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/Kay.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="13"
name="13"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ChatGPT"
image="https://sweespay.github.io/img/chat.png"
status="live"

[[CURRENCIES]]
code ="USDx"
name ="UNITED STET BOND"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="143"
name="143"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="GolD"
image="https://sweespay.github.io/img/SGB.png"
status="live"



[[CURRENCIES]]
code="1Vote"
name="Received of customers"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Received of customers"
image="https://sweespay.github.io/img/RECO.png"
status="live"


[[CURRENCIES]]
code="365"
name="365"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOSS"
image="https://sweespay.github.io/img/BOSS.png"
status="live"


[[CURRENCIES]]
code="5G"
name="5G"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOND"
image="https://sweespay.github.io/img/BOND.png"
status="live"


[[CURRENCIES]]
code="5oo"
name="5oo"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="T"
image="https://sweespay.github.io/img/T.png"
status="live"



[[CURRENCIES]]
code="69"
name="69"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="1oo"
image="https://sweespay.github.io/img/100.png"
status="live"


[[CURRENCIES]]
code="7"
name="7"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Q"
image="https://sweespay.github.io/img/Q.png"
status="live"



[[CURRENCIES]]
code="786"
name="786"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Yes"
image="https://sweespay.github.io/img/YES.png"
status="live"

[[CURRENCIES]]
code ="87"
name ="87"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000




[[CURRENCIES]]
code="92"
name="92"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="SNP500"
image="https://sweespay.github.io/img/SNP.png"
status="live"


[[CURRENCIES]]
code="990"
name="990"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="DW"
image="https://sweespay.github.io/img/DW.png"
status="live"



[[CURRENCIES]]
code="9KK"
name="9KK"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="dex"
image="https://sweespay.github.io/img/DEX.png"
status="live"



[[CURRENCIES]]
code="AI"
name="Pakistani AI"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="POK"
image="https://sweespay.github.io/img/POK.png"
status="live"


[[CURRENCIES]]
code="AKDB"
name="MASTAR"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="MASTAR"
image="https://sweespay.github.io/img/MBA.png"
status="live"



[[CURRENCIES]]
code="AKG"
name="AKG"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ALL"
image="https://sweespay.github.io/img/STAR.png"
status="live"


[[CURRENCIES]]
code="AQ"
name="AQ wallet"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="wallet"
image="https://sweespay.github.io/img/wallet.png"
status="live"



[[CURRENCIES]]
code ="BKG"
name ="BKG"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/1.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


[[CURRENCIES]]
code ="DC"
name ="DC BOND"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/2.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="BTC"
name ="THIS IS KING"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="Kay"
name ="MAKER KAY"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/Kay.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="CHATGPT"
name="ChatGPT"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ChatGPT"
image="https://sweespay.github.io/img/chat.png"
status="live"

[[CURRENCIES]]
code ="USD"
name ="UNITED STET BOND"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="GOLD"
name="Gold Bond"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="GolD"
image="https://sweespay.github.io/img/SGB.png"
status="live"



[[CURRENCIES]]
code="RCEO"
name="Received of customers"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Received of customers"
image="https://sweespay.github.io/img/RECO.png"
status="live"


[[CURRENCIES]]
code="BOSS"
name="BOSS"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOSS"
image="https://sweespay.github.io/img/BOSS.png"
status="live"


[[CURRENCIES]]
code="BOND"
name="BOND"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOND"
image="https://sweespay.github.io/img/BOND.png"
status="live"


[[CURRENCIES]]
code="T"
name="T"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="T"
image="https://sweespay.github.io/img/T.png"
status="live"



[[CURRENCIES]]
code="1oo"
name="100"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="1oo"
image="https://sweespay.github.io/img/100.png"
status="live"


[[CURRENCIES]]
code="Q"
name="Question"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Q"
image="https://sweespay.github.io/img/Q.png"
status="live"



[[CURRENCIES]]
code="Yes"
name="Yes"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Yes"
image="https://sweespay.github.io/img/YES.png"
status="live"

[[CURRENCIES]]
code ="USBS"
name ="UNIT OF USDT"
issuer = "GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://sweespay.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000




[[CURRENCIES]]
code="SNP500"
name="S&P"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="SNP500"
image="https://sweespay.github.io/img/SNP.png"
status="live"


[[CURRENCIES]]
code="DW"
name="ðŸ“›"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="DW"
image="https://sweespay.github.io/img/DW.png"
status="live"



[[CURRENCIES]]
code="DEX"
name="DX"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="dex"
image="https://sweespay.github.io/img/DEX.png"
status="live"



[[CURRENCIES]]
code="POK"
name="Pakistani Bond"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="POK"
image="https://sweespay.github.io/img/POK.png"
status="live"


[[CURRENCIES]]
code="MBA"
name="MASTAR"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="MASTAR"
image="https://sweespay.github.io/img/MBA.png"
status="live"



[[CURRENCIES]]
code="GDDSX"
name="GDDSX"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ALL"
image="https://sweespay.github.io/img/STAR.png"
status="live"


[[CURRENCIES]]
code="Wallet"
name="wallet for pay"
issuer="GBZA237FPCEA62NEIKTZ2IXVJ4W2KPULPW4YCLZGWTQVFHTTW5YYKJVV"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="wallet"
image="https://sweespay.github.io/img/wallet.png"
status="live"
